### ISSUE TITLE
convert currency doesn't work for me.

### ISSUE THREAD

**Issue by SevDrake** [hlissner/lb6-actions#33]
I have got this error Error: Error loading script: ”notify.js.”
Convert Currency.lbaction/Contents/Scripts/shared/lib/notify.js
My convert currency version is 2.2.5

**Comment by hlissner** [comment]
Sorry for the late reply.

From the sound of it, you downloaded this repo and tried to install Convert Currency.lbaction as is.

There is an extra build step: you have to run `rake` in the project root.

Otherwise, you have to download the action directly through the download link on the front page of this project's github. However, since that link is currently down, I've put the fixed, compiled action here: https://transfer.sh/W6DcU/Convert-Currency.lbaction.zip

Feel free to reopen this issue if you have further issues.

**Comment by skeskali** [comment]
When I try to download this action at the link in the previous message, a Not Found page is returned.
