### ISSUE TITLE
Convert Currency download link is unavailable

### ISSUE THREAD

**Issue by taresky** [hlissner/lb6-actions#34]
https://dl.v0.io/lb6/Convert%20Currency.lbaction.zip

**Comment by eailfly** [comment]
+1, can't access this link too

**Comment by hlissner** [comment]
Sorry for the late response. The server it was hosted on was migrated back in late May, and I've since been traveling. I return this Sunday, then I will be able to fix it and bring the links back up.

In the meantime, here is an alternative download link:

https://transfer.sh/W6DcU/Convert-Currency.lbaction.zip

I'll leave this issue open until I've addressed the issue.

**Comment by ekamran** [comment]
Both of your download links isn't working.

**Comment by eailfly** [comment]
Before this link fix, you can download it from repo, install it, and copy `shared` from repo and put it in ` ~/Library/Application Support/LaunchBar/Actions/Convert Currency.lbaction/Contents/Scripts/`, than this action should work

**Comment by ekamran** [comment]
> Before this link fix, you can download it from repo, install it, and copy `shared` from repo and put it in ` ~/Library/Application Support/LaunchBar/Actions/Convert Currency.lbaction/Contents/Scripts/`, then this action should work

It took me a while to get this working, everything is fine and rocking now.

**Comment by hlissner** [comment]
Sorry for the late response. The original download link is back up and should remain up, so I'll consider this resolved.

For posterity, here is an alternative method:

```sh
git clone --recursive https://github.com/hlissner/lb6-actions
cd lb6-actions
rake  # copy shared libraries where needed
open Convert\ Currency.lbaction  # install the action
```
